config/routes.rb
Rails.application.routes.draw do
  resources :beings
  resources :library_visits
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/being.rb
class Being < ApplicationRecord
    has_many :library_visits, dependent: :destroy
    has_many :books, through: :library_visits

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :catchphrase, presence: true
    validates :bio, length: { minimum: 50 }
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :library_visits, dependent: :destroy
    has_many :beings, through: :library_visits
end

app/models/library_visit.rb
class LibraryVisit < ApplicationRecord
  belongs_to :being
  belongs_to :book
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beings_controller.rb
class BeingsController < ApplicationController

    before_action :find_being, only: [:edit, :update, :show, :destroy]
    def index 
        @beings = Being.all
    end

    def new 
        @being = Being.new
    end
     
    def create 
        @being = Being.new(being_params)
        if @being.save
            redirect_to @being
        else 
            render :new
        end
    end

    def update 
        if @being.update(being_params)
            redirect_to @being
        else 
            render :edit
        end
    end

    def destroy 
        @being.destroy
        redirect_to beings_path
    end

    private 

    def find_being
        @being = Being.find(params[:id])
    end

    def being_params
        params.require(:being).permit(:name, :catchphrase, :bio)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
    before_action :find_book, only: :show

    def index 
        @books = Book.all
    end

    def show
        
    end

    private 

    def find_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:title, :author, :genre)
    end
end

app/controllers/library_visits_controller.rb
class LibraryVisitsController < ApplicationController

    before_action :find_lib, only: [:edit, :update, :show]

    def index 
        @libs = LibraryVisit.all
    end

    def new 
        @lib = LibraryVisit.new
    end
     
    def create 
        @lib = LibraryVisit.new(lib_params)
        if @lib.save
            redirect_to @lib
        else 
            render :new
        end 
    end

    def update 

    end

    private 

    def find_lib
        @lib = LibraryVisit.find(params[:id])
    end

    def lib_params
        params.require(:library_visit).permit(:location, :being_id, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beings_helper.rb
module BeingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/library_visits_helper.rb
module LibraryVisitsHelper
end

app/views/beings/edit.html.erb
<h1>Edit Being</h1>

<%= form_for @being do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :catchphrase %>
    <%= f.text_field :catchphrase %>
    <%= f.label :bio %>
    <%= f.text_field :bio %>
    <%= f.submit %>
<% end %>

app/views/beings/index.html.erb
<h1>Being Accounts</h1>
    <ul>
        <% @beings.each do |b| %>
        <li><%= link_to b.name, b %></li>
        <% end %>
    </ul>
<%= link_to "Create New", new_being_path %>

app/views/beings/new.html.erb
<h1>Create Being</h1>
<% if @being.errors.any? %>
<% @being.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
    <% end %>
<% end %>
<%= form_for @being do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :catchphrase %>
    <%= f.text_field :catchphrase %>
    <%= f.label :bio %>
    <%= f.text_field :bio %>
    <%= f.submit %>
<% end %>

app/views/beings/show.html.erb
<h1><%= @being.name %></h1>
<h3>Catchphrase: "<%= @being.catchphrase %>"</h3>
<h3>Bio: <%= @being.bio %></h3>
<ol>
    <h3>Books read: <% @being.books.each do |b| %></h3>
    <li><%= link_to b.title, b %></li>
    <% end %>
</ol>
<%= link_to "Edit", edit_being_path(@being) %>
<br>
<%= link_to "Return to all Beings...", beings_path %>
<%= button_to "Delete", @being, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/books/index.html.erb
<h1>All Books Ever</h1>
    <ul>
        <% @books.each do |b| %>
        <li><%= link_to b.title, b %></li>
        <% end %>
    </ul>

app/views/books/show.html.erb
<h1>Title: <%= @book.title %></h1>
<h2>Written by: <%= @book.author %></h2>
<h3>Genre: <%= @book.genre %></h3>

<%= link_to "See all books", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/library_visits/index.html.erb
<h1>Libraries of Knowledge and Thrill</h1>
    <ul>
        <% @libs.each do |l| %>
        <li><%= link_to l.location, l %></li>
        <% end %>
    </ul>
<%= link_to "Borrow a Book", new_library_visit_path %>

app/views/library_visits/new.html.erb
<h1>Borrow a Book</h1>
<%= form_for @lib do |f| %>
    <%= f.label :location %>
    <%= f.collection_select :location, LibraryVisit.all, :location, :location %>
    <%= f.label :book %>
    <%= f.collection_select :book_id, Book.all, :id, :title %>
    <%= f.label :being %>
    <%= f.collection_select :being_id, Being.all, :id, :name %>
    <%= f.submit %>
<% end %>

app/views/library_visits/show.html.erb
<h1><%= @lib.location %></h1>
<h3>Borrowed by: <%= @lib.being.name %></h3>
<h3><%= @lib.book.title %> By: <%= @lib.book.author %></h3>

<%= link_to "Back to libraries", library_visits_path %>